# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-01 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='customer_name',
        ),
    ]
