# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-01 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_database', '0003_auto_20181101_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(default='', max_length=100)),
                ('year_of_publication', models.DateField(blank=True, null=True)),
                ('magazine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine_database.Magazines')),
            ],
        ),
    ]
