# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-01 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_database', '0004_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='supplier_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
