# Generated by Django 2.1.3 on 2018-11-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magzapp', '0002_referencefrequency_ref_desciption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
