# Generated by Django 2.1.3 on 2018-11-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magzapp', '0003_auto_20181107_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='desc',
            field=models.TextField(default='default'),
        ),
    ]
