# Generated by Django 2.1.3 on 2018-11-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magzapp', '0004_magazine_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazinestatus',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
