# Generated by Django 2.1.3 on 2018-11-08 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magzapp', '0005_auto_20181108_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazinestatus',
            name='magazine_name',
        ),
        migrations.RemoveField(
            model_name='magazinestatus',
            name='user',
        ),
        migrations.DeleteModel(
            name='MagazineStatus',
        ),
    ]
