# Generated by Django 2.1.3 on 2018-11-08 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('magzapp', '0007_magazinestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='photo',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
