# Generated by Django 2.1.3 on 2018-11-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magzapp', '0008_users_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='due',
            field=models.IntegerField(default=0),
        ),
    ]
