# Generated by Django 2.1.3 on 2018-11-08 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magzapp', '0009_users_due'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='magazinestatus',
            unique_together={('magazine_name', 'user')},
        ),
    ]
