# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-31 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_invoices',
            name='other_invoice_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer_phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='other_customer_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='invoice_line_items',
            name='date_magazine_delivered',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='ref_frequencies',
            name='frequency_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
