# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-31 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_database', '0002_auto_20181031_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customer_phone',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
