# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-31 14:58
from __future__ import unicode_literals

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_database', '0003_auto_20181031_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='id',
            field=models.AutoField(auto_created=True, default=builtins.id, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
