# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-31 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_database', '0005_auto_20181031_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_invoices',
            name='customer_id',
        ),
    ]
