# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-31 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_database', '0006_remove_customer_invoices_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_invoices',
            name='customer_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='magazine_database.Customers'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
